dist: trusty

sudo: false

language: php

php:
  - "7.1"

matrix:
  fast_finish: true

env:
  - SYMFONY_VERSION="4.3.*" DB=mysql

install: true

before_script:
  # Additional PHP config
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer require symfony/test-pack
  - composer require phpunit/phpunit

# commands that will verify build
script:
  - ./vendor/bin/phpunit tests/ --testdox -v

# Customize when the notification emails are sent.
notifications:
  email:
    recipients:
      - angelyx@live.fr
    on_success: never # default: change
    on_failure: always # default: always

# safelist
branches:
  only:
    - master
    - dev

cache:
  pip: true
  directories:
    - $HOME/.composer/cache/